Added vinyl ... gulp dependency.
  Changes to be committed:
	modified:   package.json

bob@squids:~/Development/the-sign-up$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bob/Development/the-sign-up/node_modules/gulp-concat/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
bob@squids:~/Development/the-sign-up$ npm install --save vinyl
vinyl@0.4.6 node_modules/vinyl
├── clone-stats@0.0.1
└── clone@0.2.0